### ISSUE TITLE
LiveSplit integration

### ISSUE THREAD

**Issue by ghost** [1up-dev/multimario-stats#50]
LiveSplit server or component that sends star count information to the stats program.
Information sent either through Twitch chat or, ideally, through an external server to avoid message rate limiting and Twitch interface changes.
Checks split names for star counts in parentheses, or have a mapping between split titles and star counts that the user may fill in themselves.
Current implementation to reference: **[DNVIC/602-counting-bot](https://github.com/DNVIC/602-counting-bot)**

**Comment by 1up-dev** [comment]
Initial plans and investigation in #129.
