### ISSUE TITLE
Automatically clip each racer's channel when they finish

### ISSUE THREAD

**Issue by ghost** [1up-dev/multimario-stats#92]
- Use the API: https://dev.twitch.tv/docs/api/clips/
- Wait a few seconds before creating the clip, to capture more of the reaction.
- Timing of clip creation will depend on the accuracy of the final count command.
- Need to switch to a User Access Token instead of an App Access Token. This will require a Twitch user to log in and press Authorize on a browser window to get the token. Flow: https://dev.twitch.tv/docs/authentication/getting-tokens-oauth/#authorization-code-grant-flow. Set up a short-lived lightweight webserver on localhost to capture the token.
**Twitch info**: You may only capture clips if the broadcaster is streaming, has enabled clips, and hasn’t enabled the follower-only or subscribers-only clips settings (or if they have, you are a subscriber or a follower that has followed the broadcaster the required amount of time).

**Comment by 1up-dev** [comment]
Completed in commit 15323266121fc6da8f9056aec3662e7b2ebd53ed
