### ISSUE TITLE
Rate limit chat joins/parts

### ISSUE THREAD

**Issue by ghost** [1up-dev/multimario-stats#95]
It's an issue when !fetchracers finds a large number (>20) of new or old racers to edit.
The rate limit is 20 join attempts per 10 seconds.
It also may separately be an issue when reconnecting quickly multiple times in succession due to errors (mentioned in #91)

**Comment by 1up-dev** [comment]
First part completed in 295e74035db4ed18b56d73ea8dc378d8617964f3
